compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 58c466821a3277e31371feb614f1dbe3497457aea3fdb8f7fbf5c7ded152ed1c0b448a9f366e96e6441183c4fadbf82e40f2bc2f016d152990d979a490064a11
    path: .yarn/plugins/@yarnpkg/plugin-post-install.cjs
    spec: bundles/@yarnpkg/plugin-post-install.js

yarnPath: .yarn/releases/yarn-4.1.0.cjs
