nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-post-install-dev.js
    spec: bundles/@yarnpkg/plugin-post-install-dev.js

yarnPath: .yarn/releases/yarn-3.2.0.cjs
